version: '3.8'
services:
  admin_panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - admin_backend
    networks:
      - mynetwork

  admin_backend:
    build:
      context: ./admin_backend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=imoo125
      - DB_NAME=medifast
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: imoo125
      MYSQL_DATABASE: medifast
    ports:
      - "3306:3306"
    volumes:
      - /home/wadeed-ur-rahman/Documents/Admin_Panel/medifast.sql:/docker-entrypoint-initdb.d/medifast.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
